# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play (DEV - Alpha Track)"
  lane :deploy_dev do
    upload_to_play_store(
      package_name: "io.forsta.relay.dev",
      track: "alpha",
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      apk: "deploy.apk"
    )
  end

  desc "Deploy a new version to the Google Play (Production - BETA Track)"
  lane :deploy_prod do
    upload_to_play_store(
      package_name: "io.forsta.relay",
      track: "beta",
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      apk: "deploy.apk"
    )
  end

end
